config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'chat', to: 'chat#index'

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/history.rb
class History < ApplicationRecord
  validates :task, presence: true
  validates :user, presence: true
  validates :user_prompt, presence: true
  validates :completion, presence: true

  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  validates :label, presence: true
  validates :system_prompt, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    flash[:notice] = "Registrations are not currently allowed."
    redirect_to root_path
  end

  def create
    flash[:notice] = "Registrations are not currently allowed."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chat/index.html.erb
<script>
  function resizeTextArea(textarea) {
    textarea.style.height = 'auto'; // Reset the height to auto
    textarea.style.height = textarea.scrollHeight + 'px'; // Set the height based on the scroll height

    // Make sure the height does not exceed 200px
    if (textarea.scrollHeight > 200) {
      textarea.style.height = '200px';
      textarea.style.overflowY = 'scroll';
    } else {
      textarea.style.overflowY = 'hidden';
    }
  }
</script>

<style>
  /* Customize the scrollbar for WebKit-based browsers */
  textarea::-webkit-scrollbar {
    width: 8px;
    background-color: transparent;
  }

  textarea::-webkit-scrollbar-thumb {
    background-color: rgba(229, 231, 235, 0.5); /* text-gray-200 with some transparency */
    border-radius: 5px;
  }

  /* Customize the scrollbar for Firefox */
  textarea {
    scrollbar-color: rgba(229, 231, 235, 0.5) transparent;
    scrollbar-width: thin;
  }
</style>

<div class="overflow-hidden w-full h-full relative flex">
  <div class="flex h-full max-w-full flex-1 flex-col overflow-hidden">
    <main class="relative h-full w-full transition-width flex flex-col overflow-hidden items-stretch flex-1">
      <div class="flex-1 overflow-hidden">
        <div class="h-full overflow-y-auto dark:bg-gray-800">
          <div class="h-full">
            <div class="px-2 py-10 relative w-full flex flex-col h-full">
              <div class="flex items-center justify-center gap-2">
                <div class="relative w-full md:w-1/2 lg:w-1/3 xl:w-1/4">
                  <div class="relative text-center mb-8">
                    <label for="tasks" class="block text-lg font-medium dark:text-gray-200">Tasks</label>
                    <div class="relative w-full flex rounded-md border border-black/10 bg-white dark:border-white/20 dark:bg-gray-800 sm:text-sm">
                      <select id="tasks" class="dark:text-gray-200 appearance-none w-full py-2 pl-3 pr-10 text-left focus:border-green-600 focus:outline-none focus:ring-1 focus:ring-green-600 cursor-pointer rounded-md bg-transparent">
                        <% @tasks.each do |task| %>
                          <option class="dark:text-black" value="<%= task.system_prompt %>" <%= "selected" if task.label == "Chat (GPT-4)" %>>
                                <%= task.label %>
                              </option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <h1 class="text-4xl font-semibold text-center text-gray-200 dark:text-gray-600 ml-auto mr-auto mb-10 sm:mb-16 flex gap-2 items-center justify-center flex-grow">MattGPT<span class="bg-yellow-200 text-yellow-900 py-0.5 px-1.5 text-xs md:text-sm rounded-md uppercase">Plus</span></h1>
              </div>
              <div class="flex flex-col items-center text-sm dark:bg-gray-800"></div>
            </div>
          </div>
        </div>
        <div class="absolute bottom-0 left-0 w-full border-t md:border-t-0 dark:border-white/20 md:border-transparent md:dark:border-transparent md:bg-vert-light-gradient bg-white dark:bg-gray-800 md:!bg-transparent dark:md:bg-vert-dark-gradient pt-2">
          <div class="stretch mx-2 mb-2 text-center text-xs text-gray-600 dark:text-gray-200 md:mx-4 md:text-sm lg:m-auto lg:max-w-3xl">MattGPT currently has no cap on messages.</div>
          <form class="stretch mx-2 flex flex-row gap-3 last:mb-2 md:mx-4 md:last:mb-6 lg:mx-auto lg:max-w-2xl xl:max-w-3xl">
            <div class="relative flex h-full flex-1 items-stretch md:flex-col">
              <div class="">
                <div class="h-full flex ml-1 md:w-full md:m-auto md:mb-2 gap-0 md:gap-2 justify-center"></div>
              </div>
              <div class="flex flex-col w-full py-2 flex-grow md:py-3 md:pl-4 relative border border-black/10 dark:border-gray-900/50 rounded-md bg-gray-900 text-white shadow-[0_0_15px_rgba(0,0,0,0.10)] dark:bg-gray-900 dark:text-white dark:shadow-[0_0_15px_rgba(0,0,0,0.10)]">
                <textarea
  tabindex="0"
  data-id="root"
  oninput="resizeTextArea(this)"
  style="max-height: 200px; height: 24px; overflow-y: hidden;"
  rows="1"
  placeholder="Send a message."
  class="m-0 w-full resize-none border-0 bg-transparent p-0 pr-7 focus:ring-0 focus-visible:ring-0 dark:bg-transparent pl-2 md:pl-0"
></textarea>
                <button class="cursor-pointer absolute p-1 rounded-md text-gray-500 bottom-1.5 md:bottom-2.5 hover:bg-gray-100 enabled:dark:hover:text-gray-400 dark:hover:bg-gray-900 disabled:hover:bg-transparent dark:disabled:hover:bg-transparent right-1 md:right-2 disabled:opacity-40">
                  <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 mr-1" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
                </button></div>
            </div>
          </form>
          <div class="px-3 pb-3 pt-2 text-center text-xs text-gray-600 dark:text-gray-300 md:px-4 md:pb-6 md:pt-3"><span>MattGPT may produce inaccurate information about people, places, or facts. <a href="https://groff.dev" target="_blank" rel="noreferrer" class="underline">Matt Groff's Dev Blog groff.dev</a></span></div>
        </div>
      </main>
    </div>
  </div>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Welcome to Matt-GPT</h1>
  <p>Experience the power of GPT-based chat.</p>
</div>

<% if user_signed_in? %>
  <%= link_to 'Chat', chat_path %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MattGpt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://kit.fontawesome.com/70ef77e534.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script>
      // Toggle dark mode based on user preference
      const prefersDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

      if (prefersDarkMode || true) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    </script>
    <main class="h-screen w-screen">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>